"""
Gruha Alankara — Pydantic Schemas for Agent Communication

Defines the data contracts for agent tasks, results, execution plans,
critic feedback, and inter-agent messages.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Enums
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class TaskStatusEnum(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    RETRYING = "retrying"
    CANCELLED = "cancelled"


class TaskPriority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Agent Task
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class AgentTask(BaseModel):
    """Input to any agent."""

    task_id: str = Field(description="Unique task identifier")
    task_type: str = Field(description="Type of task (e.g., 'analyze_room', 'generate_design')")
    agent_name: str = Field(description="Target agent name")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Task-specific parameters")
    context: Dict[str, Any] = Field(default_factory=dict, description="Shared context from previous agents")
    constraints: Dict[str, Any] = Field(default_factory=dict, description="Constraints (budget, style, etc.)")
    priority: TaskPriority = Field(default=TaskPriority.MEDIUM)
    max_retries: int = Field(default=3)
    timeout_seconds: int = Field(default=120)
    depends_on: List[str] = Field(default_factory=list, description="Task IDs this task depends on")
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AgentResult(BaseModel):
    """Output from any agent."""

    task_id: str = Field(description="Corresponding task ID")
    agent_name: str = Field(description="Agent that produced this result")
    status: TaskStatusEnum = Field(description="Execution status")
    data: Dict[str, Any] = Field(default_factory=dict, description="Result data")
    errors: List[str] = Field(default_factory=list, description="Error messages if failed")
    confidence_score: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence in the result")
    duration_ms: float = Field(default=0.0, description="Execution duration in ms")
    token_usage: Dict[str, int] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    retry_count: int = Field(default=0)

    @property
    def is_success(self) -> bool:
        return self.status == TaskStatusEnum.SUCCESS

    @property
    def is_failed(self) -> bool:
        return self.status == TaskStatusEnum.FAILED


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Execution Plan (Supervisor Output)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class TaskNode(BaseModel):
    """A single node in the execution DAG."""

    task_id: str = Field(description="Unique node identifier")
    agent_name: str = Field(description="Agent to execute this task")
    task_type: str = Field(description="Type of operation")
    parameters: Dict[str, Any] = Field(default_factory=dict)
    depends_on: List[str] = Field(default_factory=list, description="Task IDs that must complete first")
    priority: TaskPriority = Field(default=TaskPriority.MEDIUM)
    description: str = Field(default="", description="Human-readable task description")
    estimated_duration_s: float = Field(default=30.0)
    can_retry: bool = Field(default=True)
    max_retries: int = Field(default=3)


class ExecutionPlan(BaseModel):
    """
    Complete execution plan generated by the Supervisor.
    Represents a DAG of tasks to be executed.
    """

    plan_id: str = Field(description="Unique plan identifier")
    user_intent: str = Field(default="", description="Detected user intent summary")
    reasoning: str = Field(default="", description="Supervisor's reasoning for this plan")
    tasks: List[TaskNode] = Field(default_factory=list, description="Ordered list of tasks to execute")
    steps: List[TaskStep] = Field(default_factory=list, description="Steps for LangGraph execution")
    parallel_groups: List[List[str]] = Field(
        default_factory=list,
        description="Groups of task_ids that can run in parallel",
    )
    estimated_total_duration_s: float = Field(default=0.0)
    requires_human_input: bool = Field(default=False)
    human_input_prompt: Optional[str] = Field(default=None)

    def get_task(self, task_id: str) -> Optional[TaskNode]:
        """Find a task by its ID."""
        for task in self.tasks:
            if task.task_id == task_id:
                return task
        return None

    def get_step(self, step_id: str) -> Optional[TaskStep]:
        """Find a step by its ID."""
        for step in self.steps:
            if step.step_id == step_id:
                return step
        return None

    def get_root_tasks(self) -> List[TaskNode]:
        """Get tasks with no dependencies (entry points)."""
        return [t for t in self.tasks if not t.depends_on]

    def get_dependents(self, task_id: str) -> List[TaskNode]:
        """Get tasks that depend on the given task."""
        return [t for t in self.tasks if task_id in t.depends_on]


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Critic Feedback
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class ValidationIssue(BaseModel):
    """A single validation issue found by the Critic."""

    severity: str = Field(description="'critical', 'warning', or 'info'")
    category: str = Field(description="Issue category (budget, style, accuracy, etc.)")
    description: str = Field(description="Human-readable issue description")
    affected_agent: str = Field(description="Agent whose output has the issue")
    affected_task_id: str = Field(default="")
    suggested_fix: str = Field(default="", description="How to fix the issue")


class CriticFeedback(BaseModel):
    """Validation result from the Critic Agent."""

    workflow_id: str = Field(description="ID of the validated workflow")
    is_approved: bool = Field(description="Whether the output passes validation")
    overall_score: float = Field(ge=0.0, le=1.0, description="Overall quality score")
    issues: List[ValidationIssue] = Field(default_factory=list)
    retry_instructions: Dict[str, Any] = Field(
        default_factory=dict,
        description="Instructions for retrying failed agents: {agent_name: {task_type, modified_params}}",
    )
    reasoning: str = Field(default="", description="Critic's reasoning")
    recommendations: List[str] = Field(default_factory=list, description="Improvement suggestions")

    @property
    def has_critical_issues(self) -> bool:
        return any(i.severity == "critical" for i in self.issues)

    @property
    def needs_retry(self) -> bool:
        return not self.is_approved and bool(self.retry_instructions)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Workflow State
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class WorkflowContext(BaseModel):
    """Shared context passed through the workflow."""

    workflow_id: str
    user_id: str
    session_id: str
    user_message: str
    user_intent: str = ""
    project_id: Optional[str] = None
    image_paths: List[str] = Field(default_factory=list)
    budget: Optional[float] = None
    style: Optional[str] = None
    room_type: Optional[str] = None
    preferences: Dict[str, Any] = Field(default_factory=dict)
    chat_history: List[Dict[str, str]] = Field(default_factory=list)
    memory_context: Dict[str, Any] = Field(default_factory=dict)
    agent_results: Dict[str, AgentResult] = Field(default_factory=dict)
    execution_plan: Optional[ExecutionPlan] = None
    critic_feedback: Optional[CriticFeedback] = None
    final_response: str = ""
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Task Step (for LangGraph compatibility)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class TaskStep(BaseModel):
    """A single step in task execution for LangGraph workflows."""
    
    step_id: str = Field(description="Unique step identifier")
    step_type: str = Field(default="agent", description="Type of step (agent, condition, etc.)")
    agent_name: Optional[str] = Field(default=None, description="Agent to execute this step")
    task_type: str = Field(description="Type of task to perform")
    parameters: Dict[str, Any] = Field(default_factory=dict)
    condition: Optional[str] = Field(default=None, description="Conditional logic for branching")
    dependencies: List[str] = Field(default_factory=list, description="Step IDs this step depends on")
    next_steps: List[str] = Field(default_factory=list, description="Next possible steps")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Agent Capability Descriptor
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class AgentCapability(BaseModel):
    """Describes an agent's capabilities for the Supervisor's reasoning."""

    agent_name: str
    description: str
    capabilities: List[str]
    supported_task_types: List[str]
    input_requirements: List[str] = Field(default_factory=list)
    output_format: str = ""
    estimated_latency_s: float = 10.0
    requires_gpu: bool = False
    requires_internet: bool = False
